
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Data Workspace
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed class DataWorkspace : global::Microsoft.LightSwitch.Framework.Base.DataWorkspace<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of a DataWorkspace.  Changes can be made to data sources in the new instance independent of changes made to data sources in the default DataWorkspace.
        /// </summary>
        public DataWorkspace() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Gets the ApplicationData datasource.  This provides members to query and update data in the data source.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.ApplicationData ApplicationData
        {
            get
            {
                return global::LightSwitchApplication.DataWorkspace.DetailsClass.GetValue(this, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.ApplicationData);
            }
        }
        
        /// <summary>
        /// Gets the ProjectManagementData datasource.  This provides members to query and update data in the data source.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.ProjectManagementData ProjectManagementData
        {
            get
            {
                return global::LightSwitchApplication.DataWorkspace.DetailsClass.GetValue(this, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.ProjectManagementData);
            }
        }
        
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataWorkspaceDetails<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.ApplicationData;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataWorkspacePropertySet<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ApplicationData> ApplicationData
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.ApplicationData) as global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ApplicationData>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ProjectManagementData> ProjectManagementData
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.ProjectManagementData) as global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ProjectManagementData>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ApplicationData>.Entry
                    ApplicationData = new global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ApplicationData>.Entry(
                        "ApplicationData",
                        global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties._ApplicationData_Stub);
                private static void _ApplicationData_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DataWorkspace.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ApplicationData>.Data> c, global::LightSwitchApplication.DataWorkspace.DetailsClass d, object sf)
                {
                    c(d, ref d._ApplicationData, sf);
                }
                 
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ProjectManagementData>.Entry
                    ProjectManagementData = new global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ProjectManagementData>.Entry(
                        "ProjectManagementData",
                        global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties._ProjectManagementData_Stub);
                private static void _ProjectManagementData_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DataWorkspace.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ProjectManagementData>.Data> c, global::LightSwitchApplication.DataWorkspace.DetailsClass d, object sf)
                {
                    c(d, ref d._ProjectManagementData, sf);
                }
                 
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ApplicationData>.Data _ApplicationData;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ProjectManagementData>.Data _ProjectManagementData;
            
        }
    
        #endregion
    }
    
    #endregion
    
    #region Data Services
    
    /// <summary>
    /// Provides members to query and update data in the ApplicationData datasource.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ApplicationData : global::Microsoft.LightSwitch.Framework.Base.DataService<global::LightSwitchApplication.ApplicationData, global::LightSwitchApplication.ApplicationData.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// This constructor is used for the internal LightSwitch framework. Use DataWorkspace instead.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public ApplicationData() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceDetails<global::LightSwitchApplication.ApplicationData, global::LightSwitchApplication.ApplicationData.DetailsClass, global::LightSwitchApplication.ApplicationData.DetailsClass.PropertySet, global::LightSwitchApplication.ApplicationData.DetailsClass.MethodSet>
        {
    
            static DetailsClass()
            {
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.ApplicationData.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.ApplicationData.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceMethodSet<global::LightSwitchApplication.ApplicationData, global::LightSwitchApplication.ApplicationData.DetailsClass>
            {
    
                public MethodSet() : base()
                {
                }
    
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServicePropertySet<global::LightSwitchApplication.ApplicationData, global::LightSwitchApplication.ApplicationData.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class MethodSetProperties
            {
    
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
            }
    
        }
    
        #endregion
    }
    
    /// <summary>
    /// Provides members to query and update data in the ProjectManagementData datasource.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ProjectManagementData : global::Microsoft.LightSwitch.Framework.Base.DataService<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// This constructor is used for the internal LightSwitch framework. Use DataWorkspace instead.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public ProjectManagementData() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Gets the Companies entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Company> Companies
        {
            get
            {
                return global::LightSwitchApplication.ProjectManagementData.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectManagementData.DetailsClass.PropertySetProperties.Companies);
            }
        }
        
        /// <summary>
        /// Gets the OtherActivities entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.OtherActivity> OtherActivities
        {
            get
            {
                return global::LightSwitchApplication.ProjectManagementData.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectManagementData.DetailsClass.PropertySetProperties.OtherActivities);
            }
        }
        
        /// <summary>
        /// Gets the Projects entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Project> Projects
        {
            get
            {
                return global::LightSwitchApplication.ProjectManagementData.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectManagementData.DetailsClass.PropertySetProperties.Projects);
            }
        }
        
        /// <summary>
        /// Gets the Tasks entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Task> Tasks
        {
            get
            {
                return global::LightSwitchApplication.ProjectManagementData.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectManagementData.DetailsClass.PropertySetProperties.Tasks);
            }
        }
        
        /// <summary>
        /// Gets the TaskDetails entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.TaskDetail> TaskDetails
        {
            get
            {
                return global::LightSwitchApplication.ProjectManagementData.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectManagementData.DetailsClass.PropertySetProperties.TaskDetails);
            }
        }
        
        #endregion
    
        #region Queries
    
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="CompanyId">
        /// The value of the 'CompanyId' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Company Companies_Single(global::System.Nullable<int> CompanyId)
        {
            return this.Details.Methods.Companies_Single.CreateInvocation(CompanyId).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="CompanyId">
        /// The value of the 'CompanyId' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Company Companies_SingleOrDefault(global::System.Nullable<int> CompanyId)
        {
            return this.Details.Methods.Companies_SingleOrDefault.CreateInvocation(CompanyId).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="OtherItem">
        /// The value of the 'OtherItem' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.OtherActivity OtherActivities_Single(global::System.Nullable<int> OtherItem)
        {
            return this.Details.Methods.OtherActivities_Single.CreateInvocation(OtherItem).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="OtherItem">
        /// The value of the 'OtherItem' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.OtherActivity OtherActivities_SingleOrDefault(global::System.Nullable<int> OtherItem)
        {
            return this.Details.Methods.OtherActivities_SingleOrDefault.CreateInvocation(OtherItem).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="ProjectId">
        /// The value of the 'ProjectId' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Project Projects_Single(global::System.Nullable<int> ProjectId)
        {
            return this.Details.Methods.Projects_Single.CreateInvocation(ProjectId).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="ProjectId">
        /// The value of the 'ProjectId' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Project Projects_SingleOrDefault(global::System.Nullable<int> ProjectId)
        {
            return this.Details.Methods.Projects_SingleOrDefault.CreateInvocation(ProjectId).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="TaskId">
        /// The value of the 'TaskId' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Task Tasks_Single(global::System.Nullable<int> TaskId)
        {
            return this.Details.Methods.Tasks_Single.CreateInvocation(TaskId).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="TaskId">
        /// The value of the 'TaskId' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Task Tasks_SingleOrDefault(global::System.Nullable<int> TaskId)
        {
            return this.Details.Methods.Tasks_SingleOrDefault.CreateInvocation(TaskId).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="TaskDetailId">
        /// The value of the 'TaskDetailId' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.TaskDetail TaskDetails_Single(global::System.Nullable<int> TaskDetailId)
        {
            return this.Details.Methods.TaskDetails_Single.CreateInvocation(TaskDetailId).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="TaskDetailId">
        /// The value of the 'TaskDetailId' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.TaskDetail TaskDetails_SingleOrDefault(global::System.Nullable<int> TaskDetailId)
        {
            return this.Details.Methods.TaskDetails_SingleOrDefault.CreateInvocation(TaskDetailId).Execute();
        }
        
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceDetails<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.ProjectManagementData.DetailsClass.PropertySet, global::LightSwitchApplication.ProjectManagementData.DetailsClass.MethodSet>
        {
    
            static DetailsClass()
            {
                var initializeMethodEntry = global::LightSwitchApplication.ProjectManagementData.DetailsClass.MethodSetProperties.Companies_Single;
                var initializePropertyEntry = global::LightSwitchApplication.ProjectManagementData.DetailsClass.PropertySetProperties.Companies;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.ProjectManagementData.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.ProjectManagementData.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceMethodSet<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass>
            {
    
                public MethodSet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Company> Companies_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectManagementData.DetailsClass.MethodSetProperties.Companies_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Company>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Company> Companies_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectManagementData.DetailsClass.MethodSetProperties.Companies_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Company>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.OtherActivity> OtherActivities_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectManagementData.DetailsClass.MethodSetProperties.OtherActivities_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.OtherActivity>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.OtherActivity> OtherActivities_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectManagementData.DetailsClass.MethodSetProperties.OtherActivities_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.OtherActivity>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Project> Projects_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectManagementData.DetailsClass.MethodSetProperties.Projects_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Project>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Project> Projects_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectManagementData.DetailsClass.MethodSetProperties.Projects_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Project>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Task> Tasks_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectManagementData.DetailsClass.MethodSetProperties.Tasks_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Task>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Task> Tasks_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectManagementData.DetailsClass.MethodSetProperties.Tasks_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Task>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.TaskDetail> TaskDetails_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectManagementData.DetailsClass.MethodSetProperties.TaskDetails_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.TaskDetail>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.TaskDetail> TaskDetails_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectManagementData.DetailsClass.MethodSetProperties.TaskDetails_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.TaskDetail>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServicePropertySet<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Company> Companies
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectManagementData.DetailsClass.PropertySetProperties.Companies) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Company>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.OtherActivity> OtherActivities
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectManagementData.DetailsClass.PropertySetProperties.OtherActivities) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.OtherActivity>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Project> Projects
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectManagementData.DetailsClass.PropertySetProperties.Projects) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Project>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Task> Tasks
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectManagementData.DetailsClass.PropertySetProperties.Tasks) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Task>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.TaskDetail> TaskDetails
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectManagementData.DetailsClass.PropertySetProperties.TaskDetails) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.TaskDetail>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class MethodSetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Company>.Entry
                    Companies_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Company>.Entry(
                        "Companies_Single",
                        global::LightSwitchApplication.ProjectManagementData.DetailsClass.MethodSetProperties._Companies_Single_Stub);
                private static void _Companies_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Company>.Data> c, global::LightSwitchApplication.ProjectManagementData.DetailsClass d, object sf)
                {
                    c(d, ref d._Companies_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Company>.Entry
                    Companies_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Company>.Entry(
                        "Companies_SingleOrDefault",
                        global::LightSwitchApplication.ProjectManagementData.DetailsClass.MethodSetProperties._Companies_SingleOrDefault_Stub);
                private static void _Companies_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Company>.Data> c, global::LightSwitchApplication.ProjectManagementData.DetailsClass d, object sf)
                {
                    c(d, ref d._Companies_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.OtherActivity>.Entry
                    OtherActivities_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.OtherActivity>.Entry(
                        "OtherActivities_Single",
                        global::LightSwitchApplication.ProjectManagementData.DetailsClass.MethodSetProperties._OtherActivities_Single_Stub);
                private static void _OtherActivities_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.OtherActivity>.Data> c, global::LightSwitchApplication.ProjectManagementData.DetailsClass d, object sf)
                {
                    c(d, ref d._OtherActivities_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.OtherActivity>.Entry
                    OtherActivities_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.OtherActivity>.Entry(
                        "OtherActivities_SingleOrDefault",
                        global::LightSwitchApplication.ProjectManagementData.DetailsClass.MethodSetProperties._OtherActivities_SingleOrDefault_Stub);
                private static void _OtherActivities_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.OtherActivity>.Data> c, global::LightSwitchApplication.ProjectManagementData.DetailsClass d, object sf)
                {
                    c(d, ref d._OtherActivities_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Project>.Entry
                    Projects_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Project>.Entry(
                        "Projects_Single",
                        global::LightSwitchApplication.ProjectManagementData.DetailsClass.MethodSetProperties._Projects_Single_Stub);
                private static void _Projects_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Project>.Data> c, global::LightSwitchApplication.ProjectManagementData.DetailsClass d, object sf)
                {
                    c(d, ref d._Projects_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Project>.Entry
                    Projects_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Project>.Entry(
                        "Projects_SingleOrDefault",
                        global::LightSwitchApplication.ProjectManagementData.DetailsClass.MethodSetProperties._Projects_SingleOrDefault_Stub);
                private static void _Projects_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Project>.Data> c, global::LightSwitchApplication.ProjectManagementData.DetailsClass d, object sf)
                {
                    c(d, ref d._Projects_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Task>.Entry
                    Tasks_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Task>.Entry(
                        "Tasks_Single",
                        global::LightSwitchApplication.ProjectManagementData.DetailsClass.MethodSetProperties._Tasks_Single_Stub);
                private static void _Tasks_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Task>.Data> c, global::LightSwitchApplication.ProjectManagementData.DetailsClass d, object sf)
                {
                    c(d, ref d._Tasks_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Task>.Entry
                    Tasks_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Task>.Entry(
                        "Tasks_SingleOrDefault",
                        global::LightSwitchApplication.ProjectManagementData.DetailsClass.MethodSetProperties._Tasks_SingleOrDefault_Stub);
                private static void _Tasks_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Task>.Data> c, global::LightSwitchApplication.ProjectManagementData.DetailsClass d, object sf)
                {
                    c(d, ref d._Tasks_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.TaskDetail>.Entry
                    TaskDetails_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.TaskDetail>.Entry(
                        "TaskDetails_Single",
                        global::LightSwitchApplication.ProjectManagementData.DetailsClass.MethodSetProperties._TaskDetails_Single_Stub);
                private static void _TaskDetails_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.TaskDetail>.Data> c, global::LightSwitchApplication.ProjectManagementData.DetailsClass d, object sf)
                {
                    c(d, ref d._TaskDetails_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.TaskDetail>.Entry
                    TaskDetails_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.TaskDetail>.Entry(
                        "TaskDetails_SingleOrDefault",
                        global::LightSwitchApplication.ProjectManagementData.DetailsClass.MethodSetProperties._TaskDetails_SingleOrDefault_Stub);
                private static void _TaskDetails_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.TaskDetail>.Data> c, global::LightSwitchApplication.ProjectManagementData.DetailsClass d, object sf)
                {
                    c(d, ref d._TaskDetails_SingleOrDefault, sf);
                }
    
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Company>.Entry
                    Companies = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Company>.Entry(
                        "Companies",
                        global::LightSwitchApplication.ProjectManagementData.DetailsClass.PropertySetProperties._Companies_Stub);
                private static void _Companies_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Company>.Data> c, global::LightSwitchApplication.ProjectManagementData.DetailsClass d, object sf)
                {
                    c(d, ref d._Companies, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.OtherActivity>.Entry
                    OtherActivities = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.OtherActivity>.Entry(
                        "OtherActivities",
                        global::LightSwitchApplication.ProjectManagementData.DetailsClass.PropertySetProperties._OtherActivities_Stub);
                private static void _OtherActivities_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.OtherActivity>.Data> c, global::LightSwitchApplication.ProjectManagementData.DetailsClass d, object sf)
                {
                    c(d, ref d._OtherActivities, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Project>.Entry
                    Projects = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Project>.Entry(
                        "Projects",
                        global::LightSwitchApplication.ProjectManagementData.DetailsClass.PropertySetProperties._Projects_Stub);
                private static void _Projects_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Project>.Data> c, global::LightSwitchApplication.ProjectManagementData.DetailsClass d, object sf)
                {
                    c(d, ref d._Projects, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Task>.Entry
                    Tasks = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Task>.Entry(
                        "Tasks",
                        global::LightSwitchApplication.ProjectManagementData.DetailsClass.PropertySetProperties._Tasks_Stub);
                private static void _Tasks_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Task>.Data> c, global::LightSwitchApplication.ProjectManagementData.DetailsClass d, object sf)
                {
                    c(d, ref d._Tasks, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.TaskDetail>.Entry
                    TaskDetails = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.TaskDetail>.Entry(
                        "TaskDetails",
                        global::LightSwitchApplication.ProjectManagementData.DetailsClass.PropertySetProperties._TaskDetails_Stub);
                private static void _TaskDetails_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.TaskDetail>.Data> c, global::LightSwitchApplication.ProjectManagementData.DetailsClass d, object sf)
                {
                    c(d, ref d._TaskDetails, sf);
                }
     
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Company>.Data _Companies;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.OtherActivity>.Data _OtherActivities;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Project>.Data _Projects;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Task>.Data _Tasks;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.TaskDetail>.Data _TaskDetails;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Company>.Data _Companies_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Company>.Data _Companies_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.OtherActivity>.Data _OtherActivities_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.OtherActivity>.Data _OtherActivities_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Project>.Data _Projects_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Project>.Data _Projects_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Task>.Data _Tasks_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.Task>.Data _Tasks_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.TaskDetail>.Data _TaskDetails_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ProjectManagementData, global::LightSwitchApplication.ProjectManagementData.DetailsClass, global::LightSwitchApplication.TaskDetail>.Data _TaskDetails_SingleOrDefault;
            
        }
    
        #endregion
    }
    
    #endregion
    
}
