//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Implementation
{
    
    #region Company
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ProjectManagementData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Company :
        global::LightSwitchApplication.Company.DetailsClass.IImplementation
    {
        partial void OnCompanyIdChanged()
        {
            this.___OnPropertyChanged("CompanyId");
        }
        
        partial void OnCompanyNameChanged()
        {
            this.___OnPropertyChanged("CompanyName");
        }
        
        partial void OnAddressChanged()
        {
            this.___OnPropertyChanged("Address");
        }
        
        partial void OnCityChanged()
        {
            this.___OnPropertyChanged("City");
        }
        
        partial void OnStateChanged()
        {
            this.___OnPropertyChanged("State");
        }
        
        partial void OnZipChanged()
        {
            this.___OnPropertyChanged("Zip");
        }
        
        partial void OnCountryChanged()
        {
            this.___OnPropertyChanged("Country");
        }
        
        partial void OnStatusChanged()
        {
            this.___OnPropertyChanged("Status");
        }
        
        partial void OnWorkStartedChanged()
        {
            this.___OnPropertyChanged("WorkStarted");
        }
        
        partial void OnWorkEndedChanged()
        {
            this.___OnPropertyChanged("WorkEnded");
        }
        
        partial void OnContactPersonChanged()
        {
            this.___OnPropertyChanged("ContactPerson");
        }
        
        partial void OnContactNumberChanged()
        {
            this.___OnPropertyChanged("ContactNumber");
        }
        
        partial void OnNotesChanged()
        {
            this.___OnPropertyChanged("Notes");
        }
        
        partial void OnIsDeletedChanged()
        {
            this.___OnPropertyChanged("IsDeleted");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Company.DetailsClass.IImplementation.Projects
        {
            get
            {
                return this.Projects;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Project> __Projects
        {
            get
            {
                if (this.___Projects == null)
                {
                    this.___Projects = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Project>(
                        this,
                        "Projects",
                        () => this._Projects,
                        e => global::System.Object.Equals(e.CompanyId, this.CompanyId));
                }
                return this.___Projects;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Project> ___Projects;
        
    }
    #endregion
    
    #region OtherActivity
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ProjectManagementData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class OtherActivity :
        global::LightSwitchApplication.OtherActivity.DetailsClass.IImplementation
    {
        partial void OnOtherItemChanged()
        {
            this.___OnPropertyChanged("OtherItem");
        }
        
        partial void OnTypeChanged()
        {
            this.___OnPropertyChanged("Type");
        }
        
        partial void OnDescriptionChanged()
        {
            this.___OnPropertyChanged("Description");
        }
        
        partial void OnDateTimeStartedChanged()
        {
            this.___OnPropertyChanged("DateTimeStarted");
        }
        
        partial void OnDateTimeFinishedChanged()
        {
            this.___OnPropertyChanged("DateTimeFinished");
        }
        
        partial void OnProjectIdChanged()
        {
            this.___OnPropertyChanged("ProjectId");
        }
        
    }
    #endregion
    
    #region Project
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ProjectManagementData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Project :
        global::LightSwitchApplication.Project.DetailsClass.IImplementation
    {
        partial void OnCompanyIdChanged()
        {
            this.___OnPropertyChanged("CompanyId");
            this.___OnPropertyChanged("Company");
        }
        
        partial void OnProjectIdChanged()
        {
            this.___OnPropertyChanged("ProjectId");
        }
        
        partial void OnProjectNameChanged()
        {
            this.___OnPropertyChanged("ProjectName");
        }
        
        partial void OnShortDescChanged()
        {
            this.___OnPropertyChanged("ShortDesc");
        }
        
        partial void OnLongDescChanged()
        {
            this.___OnPropertyChanged("LongDesc");
        }
        
        partial void OnPointPersonChanged()
        {
            this.___OnPropertyChanged("PointPerson");
        }
        
        partial void OnDateStartedChanged()
        {
            this.___OnPropertyChanged("DateStarted");
        }
        
        partial void OnDateFinishedChanged()
        {
            this.___OnPropertyChanged("DateFinished");
        }
        
        partial void OnStatusChanged()
        {
            this.___OnPropertyChanged("Status");
        }
        
        partial void OnAdditionalNotesChanged()
        {
            this.___OnPropertyChanged("AdditionalNotes");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Project.DetailsClass.IImplementation.Company
        {
            get
            {
                return this.Company;
            }
            set
            {
                this.Company = (global::LightSwitchApplication.Implementation.Company)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Company> __Company
        {
            get
            {
                if (this.___Company == null)
                {
                    this.___Company = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Company>(
                        this,
                        "Company",
                        new string[] { "CompanyId" },
                        e => global::System.Object.Equals(e.CompanyId, this.CompanyId),
                        () => this._Company,
                        e => this._Company = e);
                }
                return this.___Company;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Company> ___Company;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Project.DetailsClass.IImplementation.Tasks
        {
            get
            {
                return this.Tasks;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Task> __Tasks
        {
            get
            {
                if (this.___Tasks == null)
                {
                    this.___Tasks = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Task>(
                        this,
                        "Tasks",
                        () => this._Tasks,
                        e => global::System.Object.Equals(e.ProjectId, this.ProjectId));
                }
                return this.___Tasks;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Task> ___Tasks;
        
    }
    #endregion
    
    #region Task
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ProjectManagementData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Task :
        global::LightSwitchApplication.Task.DetailsClass.IImplementation
    {
        partial void OnProjectIdChanged()
        {
            this.___OnPropertyChanged("ProjectId");
            this.___OnPropertyChanged("Project");
        }
        
        partial void OnTaskIdChanged()
        {
            this.___OnPropertyChanged("TaskId");
        }
        
        partial void OnCodeIdChanged()
        {
            this.___OnPropertyChanged("CodeId");
        }
        
        partial void OnShortDescChanged()
        {
            this.___OnPropertyChanged("ShortDesc");
        }
        
        partial void OnLongDescChanged()
        {
            this.___OnPropertyChanged("LongDesc");
        }
        
        partial void OnDateTimeStartedChanged()
        {
            this.___OnPropertyChanged("DateTimeStarted");
        }
        
        partial void OnDateTimeFinishedChanged()
        {
            this.___OnPropertyChanged("DateTimeFinished");
        }
        
        partial void OnStatusChanged()
        {
            this.___OnPropertyChanged("Status");
        }
        
        partial void OnSeverityChanged()
        {
            this.___OnPropertyChanged("Severity");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Task.DetailsClass.IImplementation.Project
        {
            get
            {
                return this.Project;
            }
            set
            {
                this.Project = (global::LightSwitchApplication.Implementation.Project)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Project> __Project
        {
            get
            {
                if (this.___Project == null)
                {
                    this.___Project = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Project>(
                        this,
                        "Project",
                        new string[] { "ProjectId" },
                        e => global::System.Object.Equals(e.ProjectId, this.ProjectId),
                        () => this._Project,
                        e => this._Project = e);
                }
                return this.___Project;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Project> ___Project;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Task.DetailsClass.IImplementation.TaskDetails
        {
            get
            {
                return this.TaskDetails;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.TaskDetail> __TaskDetails
        {
            get
            {
                if (this.___TaskDetails == null)
                {
                    this.___TaskDetails = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.TaskDetail>(
                        this,
                        "TaskDetails",
                        () => this._TaskDetails,
                        e => global::System.Object.Equals(e.TaskId, this.TaskId));
                }
                return this.___TaskDetails;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.TaskDetail> ___TaskDetails;
        
    }
    #endregion
    
    #region TaskDetail
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ProjectManagementData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class TaskDetail :
        global::LightSwitchApplication.TaskDetail.DetailsClass.IImplementation
    {
        partial void OnTaskIdChanged()
        {
            this.___OnPropertyChanged("TaskId");
            this.___OnPropertyChanged("Task");
        }
        
        partial void OnTaskDetailIdChanged()
        {
            this.___OnPropertyChanged("TaskDetailId");
        }
        
        partial void OnDateTimeWorkedChanged()
        {
            this.___OnPropertyChanged("DateTimeWorked");
        }
        
        partial void OnCommentsChanged()
        {
            this.___OnPropertyChanged("Comments");
        }
        
        partial void OnTimeSpentChanged()
        {
            this.___OnPropertyChanged("TimeSpent");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TaskDetail.DetailsClass.IImplementation.Task
        {
            get
            {
                return this.Task;
            }
            set
            {
                this.Task = (global::LightSwitchApplication.Implementation.Task)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Task> __Task
        {
            get
            {
                if (this.___Task == null)
                {
                    this.___Task = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Task>(
                        this,
                        "Task",
                        new string[] { "TaskId" },
                        e => global::System.Object.Equals(e.TaskId, this.TaskId),
                        () => this._Task,
                        e => this._Task = e);
                }
                return this.___Task;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Task> ___Task;
        
    }
    #endregion
    
    #region ApplicationData
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ApplicationData
    {
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            return null;
        }
        
        protected override void InitializeDataServiceContext()
        {
            this.Format.LoadServiceModel = global::LightSwitchApplication.Implementation.ApplicationData.GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
    }
    #endregion
    
    #region ProjectManagementData
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ProjectManagementData
    {
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.Company))
            {
                return new global::LightSwitchApplication.Implementation.Company();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.OtherActivity))
            {
                return new global::LightSwitchApplication.Implementation.OtherActivity();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Project))
            {
                return new global::LightSwitchApplication.Implementation.Project();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Task))
            {
                return new global::LightSwitchApplication.Implementation.Task();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.TaskDetail))
            {
                return new global::LightSwitchApplication.Implementation.TaskDetail();
            }
            return null;
        }
        
        protected override void InitializeDataServiceContext()
        {
            this.Format.LoadServiceModel = global::LightSwitchApplication.Implementation.ProjectManagementData.GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
    }
    #endregion
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.ApplicationData();
            }
            if (dataServiceType == typeof(global::LightSwitchApplication.ProjectManagementData))
            {
                return new global::LightSwitchApplication.ProjectManagementData();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationData(global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext.CreateServiceUri("../../ApplicationData.svc"));
            }
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ProjectManagementData))
            {
                return new global::LightSwitchApplication.Implementation.ProjectManagementData(global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext.CreateServiceUri("../../ProjectManagementData.svc"));
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.Company) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Company);
            }
            if (typeof(global::LightSwitchApplication.OtherActivity) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.OtherActivity);
            }
            if (typeof(global::LightSwitchApplication.Project) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Project);
            }
            if (typeof(global::LightSwitchApplication.Task) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Task);
            }
            if (typeof(global::LightSwitchApplication.TaskDetail) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.TaskDetail);
            }
            return null;
        }
    }
}
